### ISSUE TITLE
cookie那里有问题请教

### ISSUE THREAD

**Issue by chaozai1028l** [GZhangjl/zhihu_spider#3]
debug了段start_requests()
看到cookie_dict 字典里只有 tgw_l7_route, _zap , d_c0, _xsrf 四个
但实际浏览器去看成果的请求cookie中 还需要有
/api/v3/oauth/captcha?lang=en
{"show_captcha":false}  产生的   q_c1
x-uuid 是 d_c0 的 前半部
x-xsrftoken  是 _xsrf
组成登录成功的cookie
代码中保存下来的cookie，不能继续用于爬取所需cookie吧

**Comment by GZhangjl** [comment]
![default](https://user-images.githubusercontent.com/22229320/45591600-1b554a80-b98a-11e8-9ada-eaa9b7069cbd.png)
我这边运行的话，只要登陆正常，获得的cookie也是全的，可以直接用于后续访问的，cookie不全可能是登陆的时候出了问题吧
